parameters:

services:
    custom_user_provider:
        class: <<NAMESPACEPREFIX>>\Security\Core\User\FOSUBUserProvider
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [ "@fos_user.user_manager","@doctrine.orm.entity_manager","@request_stack","@logger",{facebook: facebook_id, google: google_id}, "@mailer"]
